Update file size check jobs

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -16,11 +16,26 @@ jobs:
             - name: Checkout the code
               uses: actions/checkout@v4
 
+            #- name: Fails if any file in the PR is larger than 1 MB
+            #  id: size_check
+            #  uses: pelotech/github-action-file-size-checker@v0.1.2
+            #  with:
+            #    max_file_size_kib: '1024'
+
             - name: Fails if any file in the PR is larger than 1 MB
-              id: size_check
-              uses: pelotech/github-action-file-size-checker@v0.1.2
-              with:
-                max_file_size_kib: '1024'
+              run: |
+               for file in $(git diff --name-only origin/main); do
+                  if [ -f "$file" ]; then
+                    SIZE=$(stat -c%s "$file")
+                    SIZE_KB=$((SIZE / 1024))
+                    if [ $SIZE -gt 1048576 ]; then
+                      echo "❌ $file → ${SIZE_KB}KB exceeds 1MB"
+                      exit 1
+                    else
+                      echo "✅ $file → ${SIZE_KB}KB OK"
+                    fi
+                  fi
+                done
 
     branch-name-check:
         runs-on: ubuntu-latest
