Updated pr check workflow

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -27,9 +27,12 @@ jobs:
 
             - name: Validate Branch Name pattern
               run: |
-               echo "${{github.head_ref}}" | grep -qE "^(feature|fix|docs)/.*" \
-               && echo "Valid branch Name" || {echo "Invalid Branch name"; exit 1;}
-
+               if echo "${{ github.head_ref }}" | grep -qE "^(feature|fix|docs)/.+" ; then
+                 echo "Vaild Branch Name:" ${{github.head_ref}}
+               else 
+                 echo "Invalid Branch Name = ${{github.head_ref}}, use feature/*, fix/*, docs/*"
+                 exit 1
+               fi
 
     pr-body-check:
         runs-on: ubuntu-latest
